apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshops
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 3
    spot: false
     